### ISSUE TITLE
strictness / ES6(?) issue

### ISSUE THREAD

**Issue by b7s9** [wkdu/playlist-scraper#2]
I added "use strict"; to scraper.js which got rid of this err msg but probably created a whole array of other issues

```
$ node scraper --end 47453 --start 47400 --format csv
/Users/finch/Desktop/programming/wkdu/playlist-scraper/playlist-scraper/scraper.js:38
for (let nid = argv.start; nid <= argv.end; nid++) {
     ^^^
```

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

**Comment by pll33** [comment]
Node.js version? [Minimum supported version](https://github.com/wkdu/playlist-scraper#requirements) is v6.7.0

**Comment by b7s9** [comment]
oh geez

```
v4.6.1
```

**Comment by pll33** [comment]
Definitely upgrade node.js and those errors won't come up anymore, latest version is v8.9.1 LTS or v9.2.0 current ([see Node.js ES6/ES2015 compatibility table](http://node.green/))

If you need v4.6.1 for a specific project, check out ["nvm"](https://github.com/creationix/nvm) where you can multiple versions of node installed.

**Comment by pll33** [comment]
Reason for closing issue: unsupported Node.js version
